<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Cornell in Vietnam | Classes and Faculty</title>
        <link rel="stylesheet" type="text/css" href="../css/style.css">
    </head>
<body>
	<?php
		include("../includes/header.php");
   		include("../includes/nav_pages.php");

	//    require_once ("../includes/config.php");
	//    $mysqli = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
	//    
	//    if($mysqli->connect_error) {
	//        die("Connection failed: " . $mysqli->connect_error);
	//    } else {
	//        echo NULL;
	//    }
	?>
	<div class="page-content">
		<div class="page-heading">Classes and Faculty</div>
		<div class="page-heading-2">Faculty Leaders</div>
			
            <button class="accordion">Cornell University (CU) Team</button>
            <div class="panel">
                <h4>Thúy Tranviet, PhD</h4>
                <p>Thúy Tranviet is a senior lecturer in the Department of Asian Studies, where she has taught and managed the Vietnamese Language Studies program since 2000. As an interdisciplinary scholar, her broad research interests are within the framework of international education, literary studies and international/global service-learning (ISL/GSL) encompassing development studies, gender studies, and international development. She is particularly interested in connecting and engaging ISL in all academic disciplines. Her background training includes literary &amp; language studies, Southeast Asian literature and film. At Cornell University she has established working relationships with many departments and units across campus, having many collaborations with the Southeast Asia Program, the Language Resource Center, the College of Arts and Sciences, the College of Agriculture and Life Sciences, and the office of Engaged Cornell, among others. Thúy received her Bachelor's degree from the University of California, Santa Barbara; her MA from the University of Michigan; her MS and PhD degrees from Cornell University. In designing this internationally oriented, interdisciplinary course that integrates field-based community services, she envisions it to be a great learning experience for everyone involved – students, instructors, and the community people in Vietnam. Email: tdt5@cornell.edu</p>

                <h4>Michael Hoffmann, PhD</h4>
                <p>Mike Hoffmann is the executive director of the Cornell Institute for Climate Smart Solutions (CICSS), which was created to help raise the profile of the challenges posed by a rapidly warming climate and to help those who grow our food adapt to the changing conditions as well as reduce their carbon footprint. As executive director of CICSS, he provides visionary leadership, communicates to a wide range of audiences the challenges and opportunities that come with a changing climate, and builds partnerships among public and private organizations. Previous positions he has held at Cornell include Director of the Cornell University Agricultural Experiment Station, associate dean of the College of Agriculture and Life Sciences, associate director of Cornell Cooperative Extension, and director of the New York State Integrated Pest Management Program. He is a professor in the Department of Entomology and maintains a research program focused on management of pests of vegetable crops. He received his Bachelor’s Degree from the University of Wisconsin, Masters from the University of Arizona and PhD from the University of California, Davis. Email: mph3@cornell.edu</p>
			</div>
			
            <button class="accordion">Ton Duc Thang University (TDTU) Team</button>
			<div class="panel">
                <h4>Nguyễn Văn Huệ, PhD</h4>
                <p>Nguyen Van Hue is the Director of the Center for Vietnamese Studies and Language, Ton Duc Thang University. He is the main author of a series of textbooks entitled "Vietnamese Language for Foreigners" which are used widely in Vietnam and in many other countries, including Korea, Japan, and Australia. Previously he was the Dean of the Faculty of Vietnamese Studies at the University of Social Sciences and Humanities (USSH) - Vietnam National University, Ho Chi Minh City, where he taught linguistics to undergraduate and graduate students. From 2007-2015 he taught Vietnamese at the Foreign Studies of Tokyo University, and at Ritsumeikan Asia Pacific University, Japan. Dr. Hue received his PhD from USSH - Vietnam National University, Ho Chi Minh City in 2006. Email: nguyenvanhue@tdt.edu.vn</p>
                
                <h4>Trần Trọng Giảng, MA</h4>
                <p>Trần Trọng Giảng is the Vice Director of Center for Vietnamese Studies and Language, Ton Duc Thang University. He has experience in compiling teaching materials, preparing courses and teaching Vietnamese language at the college level for nearly twenty years.  He has worked with many instructors and supervised a number of graduate students, graders and tutors.  He has coordinated (as a translator) the project titled, “Online Teaching Vietnamese for Overseas Vietnamese," funded by the Ministry of Education and Training of Vietnam.  Over the years, he has also developed pronunciation courses with a goal to make Vietnamese simple to learn.  He is proud to say that he is skillful at teaching Vietnamese pronunciation. Mr. Giang earned his M.A. from the University of Social Sciences and Humanities (USSH), Ho Chi Minh City. Email: trantronggiang@tdt.edu.vn</p>
                
                <h4>Huỳnh Thị Cẩm Châu, BA</h4>
                <p>Huynh Thi Cẩm Châu is an administrative associate at Center for Vietnamese Studies and Language, Ton Duc Thang University. Prior to coming to TDTU, she worked as a tour operator in a travel company specializing in domestic tours for Russian visitors. Having experience in the tourism sector, she developed a strong sense of organization for extra-curricular activities for foreign students at Ton Duc Thang University. Chau received her BA degree in Russian Linguistics and Literature from the University of Social Sciences and Humanities - Vietnam National University, Ho Chi Minh City in 2013. In her free time, she loves to ride her motorcycle through the countryside or coastal areas where is not far from HCMC. She loves nature, freedom, and peacefulness. “Dream as if you’ll live forever. Live as if you’ll die today “- James Dean. This quote is her philosophy of life. Email: vietnamesestudies@tdt.edu.vn. Ms. Chau has been collaborating closely with the Cornell in Vietnam Program on many administrative tasks. She will accompany the group to Ben Tre and Phan Rang in January 2017.</p>

                <h4>Trần Thị Thanh Huyền, BA</h4>
                <p>Trần thị Thanh Huyền is a lecturer at the faculty of Russian philology at the University of Social Sciences and Humanities (USSH), Ho Chi Minh City. She also works as a teaching assistant at the Center for Vietnamese Studies and Language, TDTU. Huyen loves to travel.  She has taken trips to coastal places in Vietnam and traveled to a few foreign countries.  "Travelling - it leaves you speechless, then turns you into a storyteller”.  She is going to explore the world so she can tell you her stories!  Email: tkxd0112@gmail.com. Ms. Huyen will travel to Can Tho and Phan Rang as a local program assistant for the Winter 2017 group.</p>
			</div>
        
            <button class="accordion">Can Tho University (CTU) Team</button>
			<div class="panel">
                <h4>Đặng Kiều Nhân, PhD</h4>
  				<p>Dang Kieu Nhan is a senior lecturer at Mekong Delta Development Research Institute, Can Tho University (MDI-CTU), where he teaches Msc. courses on Agricultural Systems Analysis and Research Methods. He has authored and co-authored about 25 internationally peer-reviewed journal articles and book chapters on farming systems, agricultural nutrient and water use efficiency, agricultural resources governance, livelihoods and adaptability of farmers. He co-edited the book “Sustainable Agriculture and Rural Development in the Mekong Delta” (in Vietnamese). In addition, he has coordinated and participated in several projects on integrated farming systems, sustainable management of natural resources, and climate change adaptation in the Vietnamese Mekong Delta as well as the Lower Mekong Basin.  Dr. Nhan received his Bachelor of Science degree in Agronomy from CTU in 1990;  his Master's in Water Resources Engineering from Leuven University and Brussels University, Belgium in 1999; Ph.D. in Aquaculture Production Systems from Wageningen University, the Netherlands in 2007, with the dissertation titled, "The role of a fish pond in optimizing nutrient flows in integrated agriculture-aquaculture".   Email: dknhan@ctu.edu.vn</p>
			
            
                <h4>Lê Anh Tuấn, PhD</h4>
                <p>Le Anh Tuan is the Vice Director of the Research Institute for Climate Change (DRAGON Institute-Mekong), a research unit within the Can Tho University system. He also serves as an advisor of Vietnam Rivers Network. He has been teaching in the College of Environment and Natural Resources since 1982.  His body of work includes many research projects in the fields of Water Environment and Ecosystem based approaches, climate change adaptations and mitigation in the Mekong River Delta. In 2012, he was recognized as an associate professor in the Department of Earth Sciences.  Dr. Tuan completed his B.Eng. in Water Management and Land Improvement at CTU in 1982; M.Eng. in Water Resources Engineering at Asian Institute of Technology, Bangkok, Thailand in 1990; and PhD. in Applied BioSciences and Engineering, specialized in Environmental Hydrology at Catholic University of Leuven, Belgium.  Email: latuan@ctu.edu.vn. Website: http://www.leanhtuan.com</p>
            
                <h4>Lê Đình Bích, MA</h4>
                <p>Le Dinh Bich is a lecturer at the School of Education at Can Tho University. Born in 1958 into a family of musicians (his father was a folk musician in Quang Nam province, Central Vietnam), Mr. Bich grew up playing traditional Vietnamese folk music since the age of six. After graduating from the University of Saigon, he settled in Can Tho city in 1983.  From 1984-1985 he pursued his Master’s degree in the Soviet Union (Russia).  Returning to Vietnam he continued teaching cultural studies at CTU since the early 1990s. As a songwriter, a novelist, and a poet, Mr. Bich has a deep knowledge of southern Vietnam’s traditional music and culture. He is able to play many types of traditional Vietnamese musical instruments. He specializes in the traditional music of Vietnam, particularly Don ca Tai Tu (Đờn ca tài tử), a southern music genre in the Mekong Delta.  He has spent great many years introducing Vietnamese traditional music to foreign students. One of many students he advised include Alexander M. Cannon, then a PhD student from the University of Michigan, on his doctoral research of the traditional Southern music of Vietnam. Mr. Bich's broad areas of expertise include Southeast Asia cultural studies, religions, and music development in Vietnam.</p>

                <h4>Lê Khương Ninh, PhD</h4>
                <p>Le Khuong Ninh is an associate professor at the College of Economics, Can Tho University. He completed his B.S in Agricultural Economics at CTU in 1987, and Master’s in International Economics at Groningen University, the Netherlands in 1997. He earned his PhD in Financial Economics at Groningen University, the Netherlands in 2003 (dissertation titled, “Investment by Rice Mills in Vietnam: the role of Financial Market Imperfections and Uncertainty”).  Dr. Ninh has published more than 40 articles in national and international scientific research journals. He implemented 10 international projects and published two books in Groningen University Press and Viet Nam Education Publishing House Limited Company. In 2009, Dr. Ninh was officially recognized as an associate professor in Economics. With experiences of teaching and research in nearly 30 years, he has supervised more than 60 Master’s and PhD students.</p>

                <h4>Lê Văn Lâm, PhD</h4>
                <p>Lê Văn Lâm is a lecturer in Computer Science at the College of Information and Communication Technology and Deputy Director of International Relations Department at Can Tho University. He received his Bachelor's Degree in Informatics at CTU in 1999; Master's in Information Technology at The University of Newcastle, Australia in 2005; and his PhD in Computer Science at Victoria University of Wellington, New Zealand in 2013. His research focuses on Internet security (particularly web browser security), and the Internet of Thing (particularly IOT for automation, agriculture and aquaculture). From 2013 - 2016 Dr. Lam served as Head of Information Technology Department when he worked closely with enterprises to connect industry sectors and the College on Training, Recruitment, and R&amp;D.  Since June of 2016, he has served as the Deputy Director for the Office of International Relations to help support the activities of international affairs for the CTU.  Email: lvlam@ctu.edu.vn</p>

                <h4>Lim Ngọc Hân, BS</h4>
                <p>Lim Ngoc Han has been working as the program coordinator for the Tropical Semester Program at the International Relations office at Can Tho University since 2010.  Her main responsibility is to coordinate and promote the collaborations between CTU and its foreign partners. As a program coordinator, she welcomes many students and faculty members from various international universities to CTU to study and research every year. She enjoys working and interacting with international students and faculty to help them gain successful learning experiences during their time in the Mekong Delta. Ms. Han graduated from CTU in 2010 with a B.S degree in English Education. Email:  lnhan@ctu.edu.vn</p>

                <h4>Nguyễn Hữu Chiếm, PhD</h4>
                <p>Nguyễn Hữu Chiếm is the Chair of the Department of Environment and Natural Resources Management at the College of Agriculture and Applied Biology, CTU. Born in Can Tho province, he is the eldest of ten children and the seventh generation of a Mekong Delta farming family. Dr. Chiem, whose father was a rice farmer, was the first of his family to attend college.  He decided to devote his life studying ecology and the environment for the future of agriculture in the region. He has lived in the Mekong Delta for so long and has an intimate understanding the delta’s ecology. He remembers fondly of the times when the delta was a great place of fauna and flora biodiversity, when water could be drunk directly from the sources, and when rice could be planted naturally. Now, none of this is no longer possible. A true pioneer of the Delta, Chiem studied agronomy at CTU and went on to Kyoto University, Japan to pursue his PhD degree in agro-ecology.  After completing his studies, he returned to Vietnam to establish the Department of Environment and Natural Resources Management, which he still oversees today. The department has had more than 500 college graduates and more than 100 at the master's degree level. Email: nhchiem@ctu.edu.vn</p>
                
                <h4>Nguyễn Võ Châu Ngân, PhD</h4>
                <p>Nguyen Vo Chau Ngan is an associate professor at College of Environment and Natural Resources, Can Tho University (Vietnam), where he teaches undergraduate/graduate courses on Energy and Environment, Waste Sources Inventory, Non-sources Pollution Control, and Water Supply and Water Sewage Systems. He has authored and co-authored about 15 internationally peer-reviewed journal articles and book chapters on apply agricultural residues to energy, water management on peat soil area, household biodigesters, and gas emission control. In addition, he has coordinated and participated in several projects on water management in the Mekong Delta, using biomass as sources to produce energy, apply bio-digesters at household scale, and gas emission control. Dr. Ngan received his B.S degree in Civil Engineering from Can Tho University in 1998; Msc. degree in Water Resources Engineering from Catholic University of Leuven and Free University of Brussels, Belgium in 2002; PhD in Waste Management from Technical University of Braunschweig, Germany in 2012 (thesis: Promotion of Biogas Plant Application in the Mekong Delta of Vietnam). Email: nvcngan@ctu.edu.vn</p>


                <h4>Trần Thanh Bé, PhD</h4>
                <p>Trần Thanh Bé is a reviewer for the Advisory Councils for Research and Development projects in the Mekong Delta.  Although retired, he still gives lectures and attends scientific councils in the Department of Rural Development at CTU. Dr. Bé received his Bachelor of Science degree in Agronomy from CTU in 1978; his Master's in Systems Agriculture at UWS-Hawkesbury, Australia,  in 1994 (thesis titled “Sustainability of a Rice-Shrimp Farming System in a Brackish Water Area of the Mekong Delta, Vietnam). He earned his PhD in Agriculture at University of Sydney, Australia in 2004 (dissertation titled, “Agricultural Extension in Vietnam: Alternative Institutional Arrangements”). Dr. Bé has collaborated in many research projects on rice production, farming systems, agriculture and rural development, and socioeconomic development of the Mekong Delta, as well as other international collaboration projects. In 2008 he received the Australian Alumni Award in 2008 for Research and Science by the Australian Consulate General and received the Vietnam State Medal of labour in 2010. From 2003-2015, he worked as the Director of Mekong Delta Development Institute of Can Tho University (MDI-CTU) and served as Director of Can Tho City Institute for Socio-Economic Development Studies (CIDS).  In 2015, after 37 years of working as a continuous lecturer-researcher, Dr. Be retired.</p>
                
                
            </div>
            <button class="accordion">Other Guest Lecturers</button>
			<div class="panel">
                <h4>Andrew Wyatt, PhD</h4>
  				<p> Andrew Wyatt is an Australian national who has 20 years of research and project management experience in the Mekong Region, he has a multi-disciplinary academic background in natural resource management with a Ph.D. in Political Ecology from the School of Geosciences, University of Sydney. Andrew’s academic and professional experience has been in diverse fields such as Integrated Biodiversity Conservation and Community Development, Climate Change Adaptation, Community-Based Natural Resource Management and Co-management, Integrated Water Resources Management, and Political Ecology. Over the last 15 years, he has been based in Vietnam where he has held academic and project management positions. Since 2013, he has worked for International Union for Conservation of Nature (IUCN), Viet Nam as its Mekong Delta Program Manager, overseeing the implementation of IUCN’s major projects in the Mekong Delta. As such, he manages IUCN’s HCMC project office and provides technical oversight of IUCN’s projects working on community and ecosystem-based adaptation in the Mekong Delta. Email: Andrew.WYATT@iucn.org</p>
			</div>
	</div>

	<div class="footer-bar"><br>© SAIL 2017</div>
	<script type="text/javascript" src="../scripts/script.js"></script> 
</body>